CREATE SCHEMA IF NOT EXISTS capitoll_v2;

CREATE TABLE IF NOT EXISTS capitoll_v2.bills (
    id BIGINT PRIMARY KEY,
    bill_code TEXT NOT NULL UNIQUE,
    number_code TEXT NOT NULL,
    parliament_number INTEGER NOT NULL,
    session_number INTEGER NOT NULL,
    long_title_en TEXT NOT NULL,
    long_title_fr TEXT NOT NULL,
    status TEXT NOT NULL,
    passed_house_third_reading_at TIMESTAMP,
    did_reinstate_from_previous_session BOOLEAN NOT NULL DEFAULT FALSE,
    has_been_voted_on BOOLEAN NOT NULL DEFAULT FALSE,
    mp_votes_by_riding JSONB NOT NULL DEFAULT '{}'::jsonb
        CHECK (jsonb_typeof(mp_votes_by_riding) = 'object'),
    votes_by_key JSONB NOT NULL DEFAULT '{}'::jsonb
        CHECK (jsonb_typeof(votes_by_key) = 'object'),
    CONSTRAINT bills_bill_code_canonical_check
        CHECK (bill_code ~ '^c-[1-9][0-9]{0,3}\([0-9]{1,2}-[0-9]\)$')
);

DO $$
BEGIN
    ALTER TABLE capitoll_v2.bills
        DROP CONSTRAINT IF EXISTS bills_bill_code_check;

    ALTER TABLE capitoll_v2.bills
        DROP CONSTRAINT IF EXISTS bills_bill_code_format_check;

    ALTER TABLE capitoll_v2.bills
        DROP CONSTRAINT IF EXISTS bills_bill_code_no_padding_check;

    UPDATE capitoll_v2.bills
    SET bill_code = regexp_replace(bill_code, '\s+', '', 'g')
    WHERE bill_code ~ '\s';

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conrelid = 'capitoll_v2.bills'::regclass
                    AND conname = 'bills_bill_code_canonical_check'
    ) THEN
        ALTER TABLE capitoll_v2.bills
                        ADD CONSTRAINT bills_bill_code_canonical_check
                        CHECK (bill_code ~ '^c-[1-9][0-9]{0,3}\([0-9]{1,2}-[0-9]\)$');
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS capitoll_v2.mps (
    person_id BIGINT PRIMARY KEY,
    official_first_name TEXT,
    official_last_name TEXT,
    ridings_by_parliament JSONB NOT NULL DEFAULT '{}'::jsonb
        CHECK (jsonb_typeof(ridings_by_parliament) = 'object'),
    parties_by_parliament JSONB NOT NULL DEFAULT '{}'::jsonb
        CHECK (jsonb_typeof(parties_by_parliament) = 'object'),
    votes_by_bill JSONB NOT NULL DEFAULT '{}'::jsonb
        CHECK (jsonb_typeof(votes_by_bill) = 'object')
);

ALTER TABLE capitoll_v2.mps
    ADD COLUMN IF NOT EXISTS official_first_name TEXT;

ALTER TABLE capitoll_v2.mps
    ADD COLUMN IF NOT EXISTS official_last_name TEXT;

CREATE TABLE IF NOT EXISTS capitoll_v2.ridings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    mps_by_parliament JSONB NOT NULL DEFAULT '{}'::jsonb
        CHECK (jsonb_typeof(mps_by_parliament) = 'object')
);

CREATE UNIQUE INDEX IF NOT EXISTS capitoll_v2_ridings_name_unique
    ON capitoll_v2.ridings (name);

CREATE TABLE IF NOT EXISTS capitoll_v2.initial_import_state (
    import_name TEXT PRIMARY KEY,
    completed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    current_parliament_number INTEGER,
    current_session_number INTEGER
);

ALTER TABLE capitoll_v2.initial_import_state
    ADD COLUMN IF NOT EXISTS current_parliament_number INTEGER;

ALTER TABLE capitoll_v2.initial_import_state
    ADD COLUMN IF NOT EXISTS current_session_number INTEGER;

CREATE TABLE IF NOT EXISTS capitoll_v2.vote_import_state (
    parliament_number INTEGER NOT NULL,
    session_number INTEGER NOT NULL,
    last_decision_division_number INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (parliament_number, session_number)
);

ALTER TABLE capitoll_v2.bills
    ADD COLUMN IF NOT EXISTS passed_house_third_reading_at TIMESTAMP;

ALTER TABLE capitoll_v2.bills
    ALTER COLUMN passed_house_third_reading_at DROP NOT NULL;

ALTER TABLE capitoll_v2.bills
    ADD COLUMN IF NOT EXISTS has_been_voted_on BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE capitoll_v2.bills
    ADD COLUMN IF NOT EXISTS mp_votes_by_riding JSONB NOT NULL DEFAULT '{}'::jsonb
        CHECK (jsonb_typeof(mp_votes_by_riding) = 'object');