CREATE SCHEMA IF NOT EXISTS capitoll_v2;

CREATE TABLE IF NOT EXISTS capitoll_v2.bills (
    id BIGINT PRIMARY KEY,
    bill_code TEXT NOT NULL UNIQUE
        CHECK (bill_code ~ '^c-[0-9]+ ?\([0-9]+-[0-9]+\)$'),
    number_code TEXT NOT NULL,
    parliament_number INTEGER NOT NULL,
    session_number INTEGER NOT NULL,
    long_title_en TEXT NOT NULL,
    long_title_fr TEXT NOT NULL,
    status TEXT NOT NULL,
    passed_house_third_reading_at TIMESTAMP,
    did_reinstate_from_previous_session BOOLEAN NOT NULL DEFAULT FALSE,
    votes_by_key JSONB NOT NULL DEFAULT '{}'::jsonb
        CHECK (jsonb_typeof(votes_by_key) = 'object')
);

CREATE TABLE IF NOT EXISTS capitoll_v2.mps (
    person_id BIGINT PRIMARY KEY,
    ridings_by_parliament JSONB NOT NULL DEFAULT '{}'::jsonb
        CHECK (jsonb_typeof(ridings_by_parliament) = 'object'),
    parties_by_parliament JSONB NOT NULL DEFAULT '{}'::jsonb
        CHECK (jsonb_typeof(parties_by_parliament) = 'object'),
    votes_by_bill JSONB NOT NULL DEFAULT '{}'::jsonb
        CHECK (jsonb_typeof(votes_by_bill) = 'object')
);

CREATE TABLE IF NOT EXISTS capitoll_v2.ridings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    mps_by_parliament JSONB NOT NULL DEFAULT '{}'::jsonb
        CHECK (jsonb_typeof(mps_by_parliament) = 'object')
);

CREATE UNIQUE INDEX IF NOT EXISTS capitoll_v2_ridings_name_unique
    ON capitoll_v2.ridings (name);

CREATE TABLE IF NOT EXISTS capitoll_v2.initial_import_state (
    import_name TEXT PRIMARY KEY,
    completed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    current_parliament_number INTEGER,
    current_session_number INTEGER
);

ALTER TABLE capitoll_v2.initial_import_state
    ADD COLUMN IF NOT EXISTS current_parliament_number INTEGER;

ALTER TABLE capitoll_v2.initial_import_state
    ADD COLUMN IF NOT EXISTS current_session_number INTEGER;

CREATE TABLE IF NOT EXISTS capitoll_v2.vote_import_state (
    parliament_number INTEGER NOT NULL,
    session_number INTEGER NOT NULL,
    last_decision_division_number INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (parliament_number, session_number)
);

ALTER TABLE capitoll_v2.bills
    ADD COLUMN IF NOT EXISTS passed_house_third_reading_at TIMESTAMP;

ALTER TABLE capitoll_v2.bills
    ALTER COLUMN passed_house_third_reading_at DROP NOT NULL;